export const about = [
  {
    id: 1,
    title: 'Profile',
    subTitle: 'Account Details',
    navigator: 'Profile',
  },
  {
    id: 2,
    title: 'Statements & Reports',
    subTitle: 'Download monthly statements',
    type: 'ionicon',
    icon: 'receipt',
    navigator: 'Statement',
  },
  {
    id: 3,
    title: 'Linked Accounts',
    subTitle: 'Manage external accounts',
    type: 'font-awesome',
    icon: 'file',
    navigator: 'Account',
  },
  {
    id: 4,
    title: 'Get Help',
    subTitle: 'get support or send feedback',
    type: 'font-awesome',
    icon: 'comments',
    navigator: 'Help',
  },
  {
    id: 5,
    title: 'Security',
    subTitle: 'Protect yourself from intruders',
    type: 'font-awesome',
    icon: 'lock',
    navigator: 'Security',
  },
  {
    id: 6,
    title: 'Referrals',
    subTitle: 'Earn money when your friend joins',
    type: 'font-awesome',
    icon: 'share',
    navigator: 'Referrals',
  },
  {
    id: 7,
    title: 'Legal',
    subTitle: 'About our contract with you',
    type: 'font-awesome',
    icon: 'book',
    navigator: 'Legal',
  },
];
